# Generated by Django 4.0.4 on 2022-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukstagram', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
